#!/usr/bin/env bash

# see https://github.com/OpenAPITools/openapi-generator/tree/08296c2b1dc732829e3aaa2c2cad7c2c8c44eb8d/modules/openapi-generator/src/main/resources/ruby-client

set -e

DIR=$(cd `dirname $0` && pwd)
WORKING_DIR="/app/ruby"

docker run --rm \
  -v "${DIR}/:/local" \
  openapitools/openapi-generator-cli:v5.3.0 generate \
    -i "/local/openapi-sdk.yaml" \
    -c "/local/openapi-config.yaml" \
    -t "/local/templates" \
    -o "/local/"

printf "\nInstalling composer dependencies ...\n"
mkdir -p "${DIR}/vendor"
bash "${DIR}/bin/php" composer install
printf "\n"

printf "Adding examples to Docs ...\n"
bash "${DIR}/bin/php" ./bin/generate-examples.php

printf "Install Ruby dependencies ...\n"
bash "${DIR}/bin/ruby" bundle

printf "Replacing strings ...\n"
docker run --rm \
  -v "${DIR}:${WORKING_DIR}" \
  -w "${WORKING_DIR}" \
  perl bash ./bin/replace

printf "Scanning for prohibited keywords ...\n"
docker run --rm \
  -v "${DIR}:${WORKING_DIR}" \
  -w "${WORKING_DIR}" \
  perl bash ./bin/scan_for

printf "Running tests ...\n"
bash "${DIR}/bin/ruby" bundle exec rspec

printf "Success!\n"
