=begin
#HelloSign API

#HelloSign v3 API

The version of the OpenAPI document: 3.0.0
Contact: apisupport@hellosign.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

require 'spec_helper'
require 'json_spec'
require_relative '../test_utils'

config = HelloSign.configure
api_client = HelloSign::ApiClient.new(config)

describe HelloSign::ReportApi do
  context 'ReportApiTest' do
    api = HelloSign::ReportApi.new

    it 'testReportCreate' do
      request_class = 'ReportCreateRequest'
      request_data = get_fixture_data(request_class)[:default]

      response_class = 'ReportCreateResponse'
      response_data = get_fixture_data(response_class)[:default]

      set_expected_response(200, JSON.dump(response_data))
      expected = api_client.convert_to_type(response_data, response_class) || ReportCreateResponse
      obj = api_client.convert_to_type(request_data, request_class) || ReportCreateRequest

      result = api.report_create(obj)

      expect(result.class.to_s).to eq("HelloSign::#{response_class}")
      expect(result.to_json).to be_json_eql(expected.to_json)
    end
  end
end
