=begin
#HelloSign API

#HelloSign v3 API

The version of the OpenAPI document: 3.0.0
Contact: apisupport@hellosign.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.0

=end

require 'openssl'

module HelloSign
  class EventCallbackHelper
    # Verify that a callback came from HelloSign.com
    #
    # @param [String] api_key
    # @param [EventCallbackRequestEvent] event
    # @return bool
    def self.is_valid(api_key, event)
      hash = OpenSSL::HMAC.hexdigest(
        "SHA256",
        api_key,
        "#{event.event_time}#{event.event_type}",
      )

      return event.event_hash === hash
    end
  end
end
